### PR TITLE
WIP: Improved types, Fixes #64, #56, #9

### LINKED ISSUE #64: Proper typescript typings
`createFactory` seems to be quite impossible to make strongly typed in Typescript, without mapped types (even when not taking into consideration the partial subtypes of snapshots)

Two sample playgrounds demonstrating some of the problems:

[fails to reassign subfields](
http://www.typescriptlang.org/play/#src=type%20Factory%3CT%3E%20%3D%20T%20%26%20%7B%20()%3A%20T%20%7D%20%7C%20T%0D%0A%0D%0Afunction%20createFactory%3CT%3E(base%3A%20T)%3A%20Factory%3CT%3E%20%26%20%7B%20()%20%3A%20T%20%7D%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Afunction%20primitive%3CT%3E(value%3A%20T)%3A%20Factory%3CT%3E%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Aconst%20A%20%3D%20createFactory(%7B%0D%0A%20%20%20%20x%3A%20primitive(3%20as%20number)%2C%0D%0A%20%20%20%20y%3A%20primitive(%22boe%22%20as%20string)%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20factory%20is%20invokable%0D%0Aconst%20a%20%3D%20A()%0D%0A%0D%0A%2F%2F%20property%20can%20be%20used%20as%20proper%20type%0D%0Aconst%20z%3A%20number%20%3D%20a.x%0D%0A%0D%0A%2F%2F%20property%20can%20be%20assigned%20to%20crrectly%0D%0Aa.x%20%3D%207%0D%0A%0D%0A%2F%2F%20wrong%20type%20cannot%20be%20assigned%0D%0Aa.x%20%3D%20%22stuff%22%20%2F%2F%20Red%20is%20ok%0D%0A%0D%0A%2F%2F%20sub%20factories%20work%0D%0Aconst%20B%20%3D%20createFactory(%7B%0D%0A%20%20%20%20sub%3A%20A%0D%0A%7D)%0D%0A%0D%0Aconst%20b%20%3D%20B()%0D%0A%0D%0A%2F%2F%20sub%20fields%20have%20proper%20type%0D%0Ab.sub.x%20%3D%204%0D%0Aconst%20d%3A%20string%20%3D%20b.sub.y%0D%0A%0D%0A%2F%2F%20sub%20fields%20can%20be%20reassigned%0D%0Ab.sub%20%3D%20A()%0D%0A)

[factories are not functions, but expose (possibly null) create method (note the `create!()`)](
http://www.typescriptlang.org/play/index.html#src=type%20Factory%3CT%3E%20%3D%20T%20%26%20%7B%20create%3F()%3A%20T%20%7D%0D%0A%0D%0Afunction%20createFactory%3CT%3E(base%3A%20T)%3A%20Factory%3CT%3E%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Afunction%20primitive%3CT%3E(value%3A%20T)%3A%20Factory%3CT%3E%20%7B%0D%0A%20%20%20%20return%20null%20as%20any%0D%0A%7D%0D%0A%0D%0Aconst%20A%20%3D%20createFactory(%7B%0D%0A%20%20%20%20x%3A%20primitive(3%20as%20number)%2C%0D%0A%20%20%20%20y%3A%20primitive(%22boe%22%20as%20string)%0D%0A%7D)%0D%0A%0D%0A%2F%2F%20factory%20is%20invokable%0D%0Aconst%20a%20%3D%20A.create!()%0D%0A%0D%0A%2F%2F%20property%20can%20be%20used%20as%20proper%20type%0D%0Aconst%20z%3A%20number%20%3D%20a.x%0D%0A%0D%0A%2F%2F%20property%20can%20be%20assigned%20to%20crrectly%0D%0Aa.x%20%3D%207%0D%0A%0D%0A%2F%2F%20wrong%20type%20cannot%20be%20assigned%0D%0Aa.x%20%3D%20%22stuff%22%20%2F%2F%20Red%20is%20ok%0D%0A%0D%0A%2F%2F%20sub%20factories%20work%0D%0Aconst%20B%20%3D%20createFactory(%7B%0D%0A%20%20%20%20sub%3A%20A%0D%0A%7D)%0D%0A%0D%0Aconst%20b%20%3D%20B.create!()%0D%0A%0D%0A%2F%2F%20sub%20fields%20have%20proper%20type%0D%0Ab.sub.x%20%3D%204%0D%0Aconst%20d%3A%20string%20%3D%20b.sub.y%0D%0A%0D%0A%2F%2F%20sub%20fields%20can%20be%20reassigned%0D%0Ab.sub%20%3D%20A.create!()%0D%0A)

Something like: https://github.com/Microsoft/TypeScript/issues/13257 could definitely help!

This is  the best I could do so far:

```javascript
type Factory<T> = T & { create?(): T }

function createFactory<T>(base: T): Factory<T> {
    return null as any
}

function primitive<T>(value: T): Factory<T> {
    return null as any
}

const A = createFactory({
    x: primitive(3 as number),
    y: primitive("boe" as string)
})

// factory is invokable
const a = A.create!()

// property can be used as proper type
const z: number = a.x

// property can be assigned to crrectly
a.x = 7

// wrong type cannot be assigned
a.x = "stuff" // Red is ok

// sub factories work
const B = createFactory({
    sub: A
})

const b = B.create!()

// sub fields have proper type
b.sub.x = 4
const d: string = b.sub.y

// sub fields can be reassigned
b.sub = A.create!()
```

### PR DESCRIPTION
**Pull request by mweststrate**
* [x] go from `A()` to `A.create()` (better typescript support, easier internal factory construction / typing)
* [x] improve basic type inference
* [x] kill `action`
* [x] fix identifiers
* [x] enable strict null checks
* [x] verify types of all factories (including non-nullable of snapshots and types)
* [x] merge `Type` & `Factory`
* [x] update readme

### CODE REVIEW

**Comment by mweststrate** [comment]
This MR also merges #59 and #61

File: src/core/types.ts [hunk 1]
```diff
@@ -26,16 +27,17 @@ export abstract class Type implements IType { // TODO: generic for config and st
...
-        return factory
+    protected initializeFactory(this: Type) {
+        return {
+            create: action(
+                this.name,
+                this.create.bind(this)
+            ),
+            type: this,
+            isFactory: true,
+            factoryName: this.name,
```
Comment (mattiamanzati) [inline src/core/types.ts]: Is this really needed? Why not use this.type.name instead? :)

File: src/core/types.ts [hunk 2]
```diff
@@ -69,3 +70,8 @@ export abstract class ComplexType extends Type {
         return this.isValidSnapshot(value)
     }
 }
+
+export function typecheck(type: IType, snapshot: any) {
+    if (!type.is(snapshot))
```
Comment (mattiamanzati) [inline src/core/types.ts]: TODO: Maybe on production build this could be removed to speedup execution, but fails with errors?

File: test/type-system.ts [hunk 3]
```diff
@@ -18,41 +18,83 @@ const createTestFactories = () => {
...
-})
\ No newline at end of file
+})
+
+test("it should do typescript type inference correctly", (t) => {
+    debugger
+    const A = createFactory({
+        x: types.number,
+        y: types.maybe(types.string),
+        method() {}
```
Comment (mattiamanzati) [inline test/type-system.ts]: TODO: Also add a computed property and a manual test for that?

File: src/core/types.ts (hunk 1 above)
Comment (mweststrate) [inline src/core/types.ts]: Nope, left it as is for now, will factor out later

File: src/core/types.ts (hunk 2 above)
Comment (mweststrate) [inline src/core/types.ts]: yep, see also #62

File: src/core/administration.ts [hunk 4]
```diff
@@ -163,7 +163,7 @@ export class Node {
 
             return fail(`Cannot add an object to a state tree if it is already part of the same or another state tree. Tried to assign an object to '${this.path}/${subpath}', but it lives already at '${getPath(child)}'`)
         }
-        const existingNode = this.getChildNode(subpath)
+        const existingNode = this.getChildMST(subpath)
         const newInstance = childFactory.create(child)
 
         if (existingNode && existingNode.type === newInstance.factory) {
```
Comment (mattiamanzati) [inline src/core/administration.ts]: TODO: Should'nt be getType(newInstance) on the right side?

File: test/type-system.ts (hunk 3 above)
Comment (mweststrate) [inline test/type-system.ts]: Done

**Comment by mweststrate** [comment]
@mattiamanzati what do you think, ok to merge? Still some todo's left, but I think the current setup is good and nice enough to cut a new release, to no longer postpone all the breaking changed :see_no_evil:

**Comment by mattiamanzati** [comment]
Uh, I think that identifier should also be changed to return a constant value instead of being a function. The reason is because the parenthesis are used on a type only if that type is generic.
I think that atm is'nt clear that
types.string("") is different from types.string
and that's why I am so happy about the .create
types.string.create("") will be more explicit and explain that is different from types.string
Since identifier relies only on a isIdentifier: true, would be neat to make that signature generic.

const Todo = t.model({
  id: t.identifier(t.string)
})

where identifier() is something like Object.assign({}, type, {isIdentifier: true}).
Typings should be fine because the identifier props will be a factory as before.

**Comment by mweststrate** [comment]
Great suggestion! Will adjust identifier

**Comment by zetoke** [comment]
Hey, guys!
Do you have estimated time for merging this PR?

**Comment by mweststrate** [comment]
today or tomorrow I think

**Comment by zetoke** [comment]
@mweststrate Cool! Thank you

**Comment by zetoke** [comment]
What is the plan about publish this to NPM?
I'm very excited to refactor my current codebase :D
