### PR TITLE
fix detaching killing nodes

### LINKED ISSUE #1173: Detaching an array eliminates all of it's children
**_Bug report_**

* [x] I've checked documentation and searched for existing issues
* [x] I've made sure my project is based on the latest MST version
* [x] Fork [this](https://codesandbox.io/s/y64pzxj01) code sandbox or another minimal reproduction. 

```detach```'ing array from ```model``` effectively eliminates all the children
```js
const Model = types.model(items: types.array(SomeModel));
const model = Model.create(items: [{}, {}, {}, ...])
const detachedItems = detach(model.items);
detachedItems[0] // is undefined
model.items = detachedItems // does nothing, as there are no items
```

**Sandbox link or minimal reproduction code**
[Reproduction](https://codesandbox.io/s/3v530zoz76)

**Describe the expected behavior**
Whole array with it's contents whould be detached, so it can be reused later on.

**Describe the observed behavior**
The array is detached and preserved, but it looses own content making its quite useless.

### PR DESCRIPTION
**Pull request by xaviergonz**
Fixes #1173

### CODE REVIEW

File: packages/mobx-state-tree/src/core/node/object-node.ts [hunk 1]
```diff
@@ -453,12 +453,17 @@ export class ObjectNode<C, S, T> extends BaseNode<C, S, T> {
...
 
-        this.environment = this.root.environment // make backup of environment
-        this.identifierCache = this.root.identifierCache!.splitCache(this)
-        this.parent!.removeChild(this.subpath)
-        this.baseSetParent(null, "")
+        const newEnv = this.root.environment
+        const newIdCache = this.root.identifierCache!.splitCache(this)
 
-        this.state = NodeLifeCycle.FINALIZED
+        try {
```
Comment (k-g-a) [inline packages/mobx-state-tree/src/core/node/object-node.ts]: Just wonder, why did it become a try/catch?

Comment (xaviergonz) [reply packages/mobx-state-tree/src/core/node/object-node.ts]: To recover properly in case the conversion to undefined upon detaching fails because it's not valid

Comment (xaviergonz) [reply packages/mobx-state-tree/src/core/node/object-node.ts]: It will rethrow the error anyway, but at least it won't leave the node in an inconsistent state
